sudo: required
services:
  - docker

before_install:
  - docker build -t kat1330/react-docker -f Dockerfile.dev .

script: 
  - docker run kat1330/react-docker npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-221954440452"
  bucker_path: "react-docker"
  access_key_id: 
      secure: "$AWS_ACCESS_KEY"
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"
  on: 
    branch: master
    